version: '3.3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
  es:
    image: elasticsearch:6.7.0
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
