AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  save_weather_forecast_data_in_elasticsearch

  Sample SAM Template for save_weather_forecast_data_in_elasticsearch

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SaveWeatherForecastDataInElasticsearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: save_weather_forecast_data_in_elasticsearch/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Environment:
        Variables:
          Env: !Ref Env
          S3_URL: !Ref S3_URL
          S3_REGION: !Ref S3_REGION
          BucketName: !Ref BucketName
          APIKEY: !Ref APIKEY

Parameters:
  # prod：本番環境 dev：開発環境（ローカル）
  Env:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: dev
  S3_URL:
    Type: String
    Default: None
  S3_REGION:
    Type: String
    Default: None
  BucketName:
    Type: String
    Default: weather_forcast_data
  APIKEY:
    Type: String
    Default: None

Outputs:
  SaveWeatherForecastDataInElasticsearchFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt SaveWeatherForecastDataInElasticsearchFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt SaveWeatherForecastDataInElasticsearchFunctionRole.Arn
